services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.5.4-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - wordpress-data:/var/www/html
      - ./wordpress/wp-content/plugins/custom:/var/www/html/wp-content/plugins/custom
      - ./wordpress/wp-content/themes/custom:/var/www/html/wp-content/themes/custom
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    build: ./nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress-data:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  wordpress-data: