#!/bin/sh
# Runs inside the `wpcli` service (profile "init").
# Idempotent: writes a marker file so it's safe to invoke more than once.
#
#   make first-run   # docker compose up -d  +  run this script once
#   make init        # just (re-)run this script
#   make reset-init  # delete the marker so the next `make init` re-imports
#   make patch       # re-apply patches only, without a full re-init
#                    (runs this script with the `patch-only` argument)
set -eu

MODE="${1:-full}"

WP_PATH="/var/www/html"
INIT_DIR="/init-data"
MARKER="$WP_PATH/wp-content/.initialized"

DB_HOST="${WORDPRESS_DB_HOST%%:*}"
DB_PORT="${WORDPRESS_DB_HOST##*:}"
[ "$DB_PORT" = "$WORDPRESS_DB_HOST" ] && DB_PORT=3306

echo "==> WordPress stack initializer"

# ---------------------------------------------------------------------------
# Patch-only mode: skip the marker check and the whole DB/uploads/plugins/
# themes import entirely - just (re-)apply patches to whatever is already
# extracted, then fix ownership. This is what makes `make patch` work even
# after a full init has already run and $MARKER exists (the normal flow
# below would otherwise exit at the marker check before ever reaching the
# patch step).
# ---------------------------------------------------------------------------
if [ "$MODE" = "patch-only" ]; then
  echo "==> Patch-only mode: applying compatibility patches without a full re-init."
  if [ -f /scripts/apply-patches.sh ]; then
    sh /scripts/apply-patches.sh
  else
    echo "==> /scripts/apply-patches.sh not found - skipping patch step."
  fi
  chown -R www-data:www-data "$WP_PATH/wp-content/uploads" "$WP_PATH/wp-content/plugins" "$WP_PATH/wp-content/themes"
  chmod -R u+rwX,g+rwX "$WP_PATH/wp-content/uploads" "$WP_PATH/wp-content/plugins" "$WP_PATH/wp-content/themes"
  echo "==> Patch-only run complete."
  exit 0
fi

if [ -f "$MARKER" ]; then
  echo "==> Already initialized ($MARKER exists) - nothing to do."
  echo "==> Run 'make reset-init' first if you want to force a re-import."
  exit 0
fi

echo "==> Waiting for wp-config.php (generated by the 'wordpress' service)..."
i=0
until [ -f "$WP_PATH/wp-config.php" ]; do
  i=$((i + 1))
  if [ "$i" -gt 60 ]; then
    echo "!! Timed out waiting for wp-config.php. Is 'docker compose up -d' running?"
    exit 1
  fi
  sleep 2
done

echo "==> Waiting for the database to accept connections..."
i=0
until mariadb-admin ping -h "$DB_HOST" -P "$DB_PORT" -u "$WORDPRESS_DB_USER" -p"$WORDPRESS_DB_PASSWORD" --silent 2>/dev/null; do
  i=$((i + 1))
  if [ "$i" -gt 60 ]; then
    echo "!! Timed out waiting for the database."
    exit 1
  fi
  sleep 2
done

# ---------------------------------------------------------------------------
# 1. Database dump: init-data/*.sql.gz
# ---------------------------------------------------------------------------
DB_DUMP=$(find "$INIT_DIR" -maxdepth 1 -iname '*.sql.gz' 2>/dev/null | sort | head -n1 || true)
if [ -n "${DB_DUMP:-}" ]; then
  echo "==> Importing database dump: $DB_DUMP"
  gunzip -c "$DB_DUMP" | mariadb -h "$DB_HOST" -P "$DB_PORT" -u "$WORDPRESS_DB_USER" -p"$WORDPRESS_DB_PASSWORD" "$WORDPRESS_DB_NAME"

  if [ -n "${PROD_URL:-}" ] && [ -n "${WP_HOME:-}" ] && [ "$PROD_URL" != "$WP_HOME" ]; then
    echo "==> Rewriting URLs: $PROD_URL -> $WP_HOME"
    wp search-replace "$PROD_URL" "$WP_HOME" --all-tables --path="$WP_PATH" --allow-root || true
  fi
else
  echo "==> No *.sql.gz dump found in init-data/ - skipping database import."
fi

# ---------------------------------------------------------------------------
# 2. Uploads: init-data/uploads*.tar.gz
#    Archive is expected to contain files/folders directly (build it with
#    `cd wp-content/uploads && tar -czf ../../init-data/uploads.tar.gz .`)
# ---------------------------------------------------------------------------
UPLOADS_ARCHIVE=$(find "$INIT_DIR" -maxdepth 1 -iname 'uploads*.tar.gz' 2>/dev/null | sort | head -n1 || true)
if [ -n "${UPLOADS_ARCHIVE:-}" ]; then
  echo "==> Extracting uploads: $UPLOADS_ARCHIVE"
  mkdir -p "$WP_PATH/wp-content/uploads"
  tar -xzf "$UPLOADS_ARCHIVE" -C "$WP_PATH/wp-content/uploads"
else
  echo "==> No uploads*.tar.gz found in init-data/ - skipping."
fi

# ---------------------------------------------------------------------------
# 3. Third-party plugins: init-data/plugins*.tar.gz
#    Extracted into the SAME wp-content/plugins/ folder as the git-tracked
#    custom plugins - they coexist as sibling directories. .gitignore keeps
#    everything except "acme-*/" folders out of version control, so this is
#    always safe to run.
# ---------------------------------------------------------------------------
PLUGINS_ARCHIVE=$(find "$INIT_DIR" -maxdepth 1 -iname 'plugins*.tar.gz' 2>/dev/null | sort | head -n1 || true)
if [ -n "${PLUGINS_ARCHIVE:-}" ]; then
  echo "==> Extracting third-party plugins: $PLUGINS_ARCHIVE"
  mkdir -p "$WP_PATH/wp-content/plugins"
  tar -xzf "$PLUGINS_ARCHIVE" -C "$WP_PATH/wp-content/plugins"
else
  echo "==> No plugins*.tar.gz found in init-data/ - skipping."
fi

# ---------------------------------------------------------------------------
# 4. Third-party themes: init-data/themes*.tar.gz
#    Extracted into the SAME wp-content/themes/ folder as the git-tracked
#    custom themes - they coexist as sibling directories. .gitignore keeps
#    everything except "acme-*/" folders out of version control, so this is
#    always safe to run.
# ---------------------------------------------------------------------------
THEMES_ARCHIVE=$(find "$INIT_DIR" -maxdepth 1 -iname 'themes*.tar.gz' 2>/dev/null | sort | head -n1 || true)
if [ -n "${THEMES_ARCHIVE:-}" ]; then
  echo "==> Extracting third-party themes: $THEMES_ARCHIVE"
  mkdir -p "$WP_PATH/wp-content/themes"
  tar -xzf "$THEMES_ARCHIVE" -C "$WP_PATH/wp-content/themes"
else
  echo "==> No themes*.tar.gz found in init-data/ - skipping."
fi

# ---------------------------------------------------------------------------
# 5. Compatibility patches: patches/plugins/<slug>/*.patch, patches/themes/<slug>/*.patch
#    Must run AFTER extraction (step 3/4) so the target files exist, and
#    BEFORE the chown below so the resulting files end up owned correctly.
# ---------------------------------------------------------------------------
if [ -f /scripts/apply-patches.sh ]; then
  sh /scripts/apply-patches.sh
else
  echo "==> /scripts/apply-patches.sh not found - skipping patch step."
fi

# ---------------------------------------------------------------------------
# Fix ownership/perms so the 'wordpress' (apache/www-data) service can read
# AND write these bind-mounted dirs (installs, uploads, future patches).
# This container runs as root (see docker-compose.yml `user: "0:0"`), which
# is what makes this chown actually succeed.
# ---------------------------------------------------------------------------
chown -R www-data:www-data "$WP_PATH/wp-content/uploads" "$WP_PATH/wp-content/plugins" "$WP_PATH/wp-content/themes"
chmod -R u+rwX,g+rwX "$WP_PATH/wp-content/uploads" "$WP_PATH/wp-content/plugins" "$WP_PATH/wp-content/themes"

mkdir -p "$(dirname "$MARKER")"
touch "$MARKER"
echo "==> Initialization complete."
